### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [jscheiny/Streams#6]
I find that include guards like "[`STREAM_H`](https://github.com/jscheiny/Streams/blob/a23f201015e29cdcf08b8e32c6e858eed85a9a08/source/Stream.h#L1)" and "[`UTILITY_H`](https://github.com/jscheiny/Streams/blob/a7b781c7434e171c5539e4537508f41cd95847c3/source/Utility.h#L1)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by jscheiny** [comment]
Thanks for reminding me to do this, keep forgetting.

**Comment by jscheiny** [comment]
Fixed by jscheiny/Streams@865cfe0 and jscheiny/Streams@26c259b

**Comment by elfring** [comment]
Thanks for [your improvement of include guards](https://github.com/jscheiny/Streams/commit/865cfe08ee6c5cb2db8f7c6940c77fb28e33e437 "More unique include guards").
